### ISSUE TITLE
Sharing Platform Search Function Does Not Work on Website

### ISSUE THREAD

**Issue by Bietola** [LMMS/lmms.io#335] opened 2021-06-15 14:19 UTC
No description is really required... as soon as I hit "search" I don't get search result but only get what seems to be a page referesh.

**Comment by Umcaruje** [comment] 2021-07-30 10:03
Confirmed. @liushuyu any insights on why this could be happening?

**Comment by liushuyu** [comment] 2021-11-22 05:58
This should have been fixed in 4aed777020bea35665f20ebeb25f9d451b22467a.

Could you please verify it? Thank you in advance.

**Comment by tresf** [comment] 2021-11-22 05:59
Seems to be fixed.

**Closed by tresf** 2021-11-22 05:59 UTC
Labels: bug, lsp
