### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by teeberg** [LMMS/lmms.io#180] opened 2016-03-27 01:27 UTC
I keep getting this error, even though I'm fairly sure I'm not blind:

<img width="862" alt="screen shot 2016-03-26 at 6 23 58 pm" src="https://cloud.githubusercontent.com/assets/199071/14063299/f1f81064-f37f-11e5-9aad-7bd763c652cb.png">

It's also *really* annoying that it doesn't remember any of the inputs.

**Comment by tresf** [comment] 2016-03-27 01:37
Our security code is rubbish (I know, I wrote it).  It uses a token from the session combined with a timestamp and that sometimes has issues from time to time.  Clearing the cache or using another browser seems to fix it, but before you do that, I'll make sure registration is working for me, delete the newly created user and then post back.

**Comment by tresf** [comment] 2016-03-27 01:40
Hmm... did you register using `teeberg`?  Your info is in the users table...

**Comment by tresf** [comment] 2016-03-27 01:46
Ok... I just registered successfully using a private browser session.... 


**Full Name:** Harman Kardon
**Username:** hkardon77
**Password:** <same>

And then it let me sign in.

Then deleted it using:

```sql
delete from users where login = 'hkardon77';
```

So it's working as expected here...

**Comment by teeberg** [comment] 2016-03-27 02:06
I managed to create my user through Firefox. It only got blocked in Chrome, potentially by some of my privacy extensions. I even tried enabling sending of the referrer though, not sure what else it's expecting.

**Comment by tresf** [comment] 2016-03-27 02:18
Really just the session.... 

https://github.com/LMMS/lmms.io/blob/master/public/lsp/register.php#L31:L44

It's more of a smokescreen though.  Quite ineffective if someone felt like writing a true brute-force.

Closing since the issue was most likely caused by a browser extension.  Proper recaptcha would be included in a major rewrite.

**Closed by tresf** 2016-03-27 02:18 UTC
