### ISSUE TITLE
LMMS sharing platform is inacessible

### ISSUE THREAD

**Issue by ZER02002** [LMMS/lmms.io#312] opened 2020-06-01 05:51 UTC
For two days now, I get a 404 error message whenever I try to access the LMMS sharing platform.
The LMMS website is working well, only the sharing platform is having issues.
Maybe a hosting server that went down.

**Comment by Spekular** [comment] 2020-06-01 07:42
Duplicate of #309 #310 #311

**Closed** 2020-06-01 15:01 UTC
