### ISSUE TITLE
Licenses for uploaded content on lmms.io

### ISSUE THREAD

**Issue by pbella** [LMMS/lmms.io#176] opened 2016-02-08 03:44 UTC
I've noticed at least some content has been uploaded to the site with a CPL license designation such as https://lmms.io/lsp/?action=show&file=7972

AFAIK, this is a deprecated license and would be incompatible with LMMS.

Also, more generally, it would be helpful if the license specified for uploaded files included hyperlinks to the specific license (esp. when there can be more than one version of a given license)

**Comment by tresf** [comment] 2016-02-08 03:52
Artwork license is quite different from code license and we're not in control of what our users submit (nor do we want to).  Furthermore, our site content isn't subject to GPL, only our codebase is.  This may sound wrong and confusing, but artists don't need to use our source code license when releasing their work.

That said, the licenses need work.  Duplicate of #54, really.

**Closed by tresf** 2016-02-08 03:52 UTC
