### ISSUE TITLE
who can set a new db parameter for auto-log-off on forum db

### ISSUE THREAD

**Issue by musikBear** [LMMS/lmms.io#154] opened 2015-03-24 17:01 UTC
I think that the time is too short. 8 hours would be apropiate for a login, before the db automatically log you out - Are there any reasons for 8 hours not to be ok?
(hub never logs out automatically, and we are much more active on hub, than on forum, the aditional 'presence' should not be a real problem?)

**Comment by Sti2nd** [comment] 2015-03-24 19:06
I am not sure any longer time will make a difference. You can still risk that you get logged out when writing something.

**Comment by Sti2nd** [comment] 2015-03-24 19:19
In general tab under security settings I found a maximum limit of 7200 seconds to submit form, don't know if that could be it.

**Comment by musikBear** [comment] 2015-03-24 19:35
Try that one Stian, but usually there is something called *auto-log-off-time* or similar.. ?
But it could be that 'submit form' time, or maybe there just aren't any setting for it :/

**Comment by Sti2nd** [comment] 2015-03-24 19:42
I'll wait for @tresf  or @Umcaruje  before doing anything

**Comment by Umcaruje** [comment] 2015-03-24 19:58
>In general tab under security settings I found a maximum limit of 7200 seconds to submit form, don't know if that could be it.

I don't think that is the setting you are looking for.

Do you want to enable persistent logins @musikBear? Is that what you're asking for? The current login length is 0 which means its disabled.

**Comment by tresf** [comment] 2015-03-24 20:05
Duplicate of #65.

**Comment by tresf** [comment] 2015-03-24 20:05
@musikBear if you know something we don't, please let us know. :+1:

**Closed by tresf** 2015-03-24 20:05 UTC

**Comment by tresf** [comment] 2015-03-24 20:07
Could this be caused by browsers such as Firefox and Chrome failing to store two passwords for the same site?  I know every time I sign into the LSP it tries using my Forums Login.  From research, there's no easy fix to this password storage problem, but I wonder if the two are related somehow?

**Comment by musikBear** [comment] 2015-03-25 14:02
@Umcaruje 
> Do you want to enable persistent logins @musikBear? Is that what you're asking for? The current login length is 0 which means its disabled.'

That could be the correct setting. It would at least be interesting to see if there was a change in behavior, if that parameter was different. Is it a *boolean* 0, or a value?
Could be that changing that to <> 0, would open more options in the log-in tab?

**Comment by tresf** [comment] 2015-03-25 18:39
Stop speculating and help us fix this or let the topic die.  Enough's enough with this guesswork.  You're way too active on our tracker to keep making duplicate bug reports and asking the developers to hold your hand.  phpBB is open source and there are plenty of tutorials and troubleshooting articles around it.  Do yourself and the community a favor and search before you post.
